appBodega/urls.py
from django.shortcuts import render, redirect
from django.urls import path
from . import views

app_name = 'appBodega'

urlpatterns =[
    path('', views.index, name='bodega'),
    path('newTecnologi/', views.newTecnologi, name='newTecnologi'),
    path('newOtros/', views.newOtros, name='newOtros'),
    path('newUbication/',views.newUbication, name='newUbication'),
    path('prestamo/', views.prestamo, name='prestamo'),
    path('mesaAyuda/', views.mesaAyuda, name='mesaAyuda'),
    path('newReport/', views.newReporte, name='newReport'),
    path('detalle/<int:id>/', views.visualizar, name='detalles'),
    path('deatelleOtros/<int:id>/', views.visualizarMaterial, name='detalleOtros'),
    path('detalle_reporte/<int:id>/',views.visualizar, name='detalle_reporte'),
    path('actualiar-equipo/<int:id>/', views.actualizarTecnologia, name='actualizar-equipo'),
    path('actualizar-otros/<int:id>/', views.actualizarMaterial, name='actualizar-otros'),
    ]

appIA/urls.py
from django.urls import path
from . import views


app_name = 'appIA'

urlpatterns = [
    path('', views.mensage, name='lora'),
    path('ia', views.mensage, name='send_message'),
    path('procesar_mensaje/', views.procesar_mensaje, name='procesar_mensaje'),
]

inventario/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views
from django.contrib.auth.views import LogoutView
urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.index, name='index'),
    path('ingresar/', views.login, name='ingresar'),
    path('gestorCentro/', include('appGestorCentro.urls'), name='gestorCentro'),
    path('bodega/', include('appBodega.urls'), name='bodega'),
    path('Lora/', include('appIA.urls'), name='ia'),
    path('ajustes/<int:id>/', views.ajustes, name='ajustes'),
    path('actualizar_datos/<int:id>/', views.modificar_usuario, name='actualizar_datos'),
    path('salir', LogoutView.as_view(next_page='ingresar'), name='salir'),
]

appMesaAyuda/models.py
from django.db import models

# Create your models here.

appMesaAyuda/views.py
from django.shortcuts import render

# Create your views here.

appMesaAyuda/templates/mesaAyuda.html
{% extends 'plantilla.html' %}
{% load static %}
{% block title %}Mesa de Ayuda{% endblock %}
{% block menuoptions %}
<li class="nav-item">
    <a class="nav-link active" aria-current="page" href="{% url 'appBodega:bodega' %}">Regresar</a>
</li>
{% endblock %}
{% block p %}
<h3>Historico de reportes</h3>
<br>
{% endblock %}
{% block contenido %}
<div class="container_graficos">
    <div class="card">{{grafico_1}}</div>
    <div class="card">{{grafico_2}}</div>
    <div class="card">{{grafico_3}}</div>
    <div class="card">{{grafico_4}}</div>
</div>
<div class="titulo-graficos">
    <h3>Casos Reportados</h3>
</div>
<div class="container_graficos">
    <div class="card"><h3>Nuevos</h3></div>
    <div class="card" id="fondoAzul"><h3>Cerrados</h3></div>
    <div class="card" id="fondoRojo"><h3>Abiertos</h3></div>
    <div class="card" id="fondoNegro"><h3>Resueltos</h3></div>
</div>
<div class="titulo-graficos">
    <h3>Asignados a {{usuario}}</h3>
</div>
<div class="container_graficos">
    <div class="card"><i class="fa-solid fa-database" id="ordenCard"></i><a href="" id="a"><h4>Asignados a ti</h4></a></div>
    <div class="card"><i class="fa-solid fa-file" id="ordenCard"></i><a href="" id="a"><h4>Mis Reportes</h4></a></div>
    <div class="card" ><i class="fa-solid fa-plus" id="ordenCard"></i><a href="{% url 'newReport' %}" id="a"><h4>Crear Reporte</h4></a></div>
</div>
<div class="titulo-graficos">
    <h3>Reportes {{estado_reporte}}</h3>
</div>
<div class="container_tabla-reporte">
    <div class="busqueda">
        <div class="filtros">
        </div>
        <div class="filtros"></div>
        <div class="filtros">
            <form method="GET" action="{% url 'appBodega:mesaAyuda' %}" class="mb-3">
                <div class="input-group">
                    <input type="text" name="search" class="form-control" placeholder="Buscar por solicitante, asignado" 
                           value="{{ search_query }}">
                    <button type="submit" class="btn btn-primary">Buscar</button>
                </div>
            </form>
        </div>
    </div>
    <table class="table table-striped table-hover">
        <thead>
            <tr>
                <th scope="col">ID</th>
                <th scope="col">Fecha</th>
                <th scope="col">Usuario</th>
                <th scope="col">Descripción</th>
                <th scope="col">Estado</th>
                <th scope="col">Acciones</th>
            </tr>
        </thead>
        <tbody>
            {% for reporte in reportes %}
            <tr>
                <th scope="row">{{ reporte.id }}</th>
                <td>{{ reporte.fecha }}</td>
                <td>{{ reporte.usuario }}</td>
                <td>{{ reporte.descripcion }}</td>
                <td>{{ reporte.estado }}</td>
                <td><a href="{% url 'appBodega:detalle_reporte' reporte.id %}">Ver Detalles</a></td>
            </tr>
            {% endfor %}
      </table>
      <div class="pagination">
        <span class="step-links">
            {% if ubicaciones.has_previous %}
                <a href="?page=1&search={{ search_query }}">&laquo; Primera</a>
                <a href="?page={{ ubicaciones.previous_page_number }}&search={{ search_query }}">Anterior</a>
            {% endif %}
    
            <span class="current">
                Página {{ ubicaciones.number }} de {{ ubicaciones.paginator.num_pages }}.
            </span>
    
            {% if ubicaciones.has_next %}
                <a href="?page={{ ubicaciones.next_page_number }}&search={{ search_query }}">Siguiente</a>
                <a href="?page={{ ubicaciones.paginator.num_pages }}&search={{ search_query }}">Última &raquo;</a>
            {% endif %}
        </span>
    </div>
</div>
<a href=""><div class="qr-code">
    <video src="{% static 'video/ia.mp4' %}" autoplay="true" muted="true" loop="true" width="50%"></video>
</div></a>

{% endblock %}