appBodega/urls.py
from django.shortcuts import render, redirect
from django.urls import path
from . import views

app_name = 'appBodega'

urlpatterns =[
    path('', views.index, name='bodega'),
    path('newTecnologi/', views.newTecnologi, name='newTecnologi'),
    path('newOtros/', views.newOtros, name='newOtros'),
    path('newUbication/',views.newUbication, name='newUbication'),
    path('prestamo/', views.prestamo, name='prestamo'),
    path('mesaAyuda/', views.mesaAyuda, name='mesaAyuda'),
    path('newReport/', views.newReporte, name='newReport'),
    path('detalle/<int:id>/', views.visualizar, name='detalles'),
    path('deatelleOtros/<int:id>/', views.visualizarMaterial, name='detalleOtros'),
    path('detalle_reporte/<int:id>/',views.visualizar, name='detalle_reporte'),
    path('actualiar-equipo/<int:id>/', views.actualizarTecnologia, name='actualizar-equipo'),
    path('actualizar-otros/<int:id>/', views.actualizarMaterial, name='actualizar-otros'),
    ]

appIA/urls.py
from django.urls import path
from . import views


app_name = 'appIA'

urlpatterns = [
    path('', views.mensage, name='lora'),
    path('ia', views.mensage, name='send_message'),
    path('procesar_mensaje/', views.procesar_mensaje, name='procesar_mensaje'),
]

inventario/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views
from django.contrib.auth.views import LogoutView
urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.index, name='index'),
    path('ingresar/', views.login, name='ingresar'),
    path('gestorCentro/', include('appGestorCentro.urls'), name='gestorCentro'),
    path('bodega/', include('appBodega.urls'), name='bodega'),
    path('Lora/', include('appIA.urls'), name='ia'),
    path('ajustes/<int:id>/', views.ajustes, name='ajustes'),
    path('actualizar_datos/<int:id>/', views.modificar_usuario, name='actualizar_datos'),
    path('salir', LogoutView.as_view(next_page='ingresar'), name='salir'),
]

appBodega/models.py
from django.db import models

# Create your models here.

appBodega/forms.py
from django import forms
from inventario.models import centro,User, Rol, TypeDocument, Password, Ubication, Type_technologi, Markes, Place, Material_Didactico, Lend
from inventario import models
from django.core.validators import RegexValidator, EmailValidator


class RegistroUbicacion(forms.ModelForm):
    name_validator = RegexValidator(
        regex=r'^[A-Za-zÁÉÍÓÚáéíóúÑñ ]+$',
        message="Solo se permiten letras y espacios."
    )

    id_centro = forms.ModelChoiceField(
        queryset =centro.objects.all(),
        label='Centro al que pertenece',
        empty_label='Seleccione una opción',
        widget=forms.Select(attrs={'class': 'form-select'})
    )

    name_Ubication = forms.CharField(
        max_length=100,
        label="Nombre de la Ubicación",
        widget=forms.TextInput(attrs={'class': 'form-control'})
    )

    description_ubication = forms.CharField(
    max_length=200,
    label="Descripción de la Ubicación",
    widget=forms.Textarea(attrs={'class': 'form-control', 'rows': 3})
    )

    class Meta:
        model = models.Ubication
        fields = ['id_centro','name_Ubication','description_ubication']


class RegistroTecnologico(forms.ModelForm):
    idType_technologi = forms.ModelChoiceField(
        queryset =models.Type_technologi.objects.all(),
        label='Tipo de Elemento',
        empty_label='Seleccione una opción',
        widget=forms.Select(attrs={'class': 'form-select'})
    )
   
    caracteristics = forms.CharField(
    max_length=200,
    label="Caracteristicas",
    widget=forms.Textarea(attrs={'class': 'form-control', 'rows': 3})
    )

    idMarke = forms.ModelChoiceField(
        queryset =models.Markes.objects.all(),
        label='Marca',
        empty_label='Seleccione una opción',
        widget=forms.Select(attrs={'class': 'form-select'})
    )
    series_Manufactures = forms.CharField(
    max_length=200,
    label="Serial Fabrica",
    widget=forms.Textarea(attrs={'class': 'form-control', 'rows': 3})
    )

    series_sena = forms.CharField(
    max_length=200,
    label="Serial Sena",
    widget=forms.Textarea(attrs={'class': 'form-control', 'rows': 3})
    )

    idUbication = forms.ModelChoiceField(
        queryset =models.Ubication.objects.all(),
        label='Ubicación',
        empty_label='Seleccione una opción',
        widget=forms.Select(attrs={'class': 'form-select'})
    )

    id_Place = forms.ModelChoiceField(
        queryset =models.Place.objects.all(),
        label='Estado',
        empty_label='Seleccione una opción',
        widget=forms.Select(attrs={'class': 'form-select'})
    )

    class Meta:
        model= models.Tecnology
        fields = ['idType_technologi','caracteristics','idMarke','series_Manufactures','series_sena','idUbication','id_Place']


class RegistroMateriales(forms.ModelForm):
    name_material = forms.CharField(
        label='Nombre del Material',
        max_length=100,
        widget=forms.TextInput(attrs={'class': 'form-control'})
    )
    

    description = forms.CharField(
    max_length=200,
    label="Descripción",
    widget=forms.Textarea(attrs={'class': 'form-control', 'rows': 1})
    )

    quantity = forms.IntegerField(
        label='Cantidad',
        widget=forms.NumberInput(attrs={'class': 'form-control'})
    )

    series_Manufactures = forms.CharField(
    max_length=200,
    label="Serial Fabrica",
    widget=forms.Textarea(attrs={'class': 'form-control', 'rows': 1})
    )

    series_sena = forms.CharField(
    max_length=200,
    label="Serial SENA",
    widget=forms.Textarea(attrs={'class': 'form-control', 'rows': 1})
    )

    id_Place=forms.ModelChoiceField(
        queryset = models.Place.objects.all(),
        label='Ubicación',
        empty_label='Seleccione una opción',
        widget=forms.Select(attrs={'class': 'form-select'})
    )
    

    class Meta:
        model = models.Material_Didactico
        fields =['name_material','description','quantity','series_Manufactures','series_sena','id_Place']


class Prestamo(forms.ModelForm):
    id_technologi = forms.ModelChoiceField(
        queryset =models.Tecnology.objects.all(),
        label='Elemento Tecnológico',
        empty_label='Seleccione una opción',
        widget=forms.Select(attrs={'class': 'form-select'})
    )

    id_user = forms.ModelChoiceField(
        queryset =User.objects.all(),
        label='Usuario',
        empty_label='Seleccione una opción',
        widget=forms.Select(attrs={'class': 'form-select'})
    )

    idMaterial_didactico = forms.ModelChoiceField(
        queryset =models.Material_Didactico.objects.all(),
        label='Material Didáctico',
        empty_label='Seleccione una opción',
        widget=forms.Select(attrs={'class': 'form-select'})
    )

    observation = forms.CharField(
    max_length=200,
    label="Descripción",
    widget=forms.Textarea(attrs={'class': 'form-control', 'rows': 1})
    )
    class Meta:
        model = models.Lend
        fields = ['id_user','id_technologi','idMaterial_didactico','observation']


class ReporteForm(forms.ModelForm):
    class Meta:
        model = models.Report
        fields = '__all__'
        widgets = {
            }

appBodega/views.py
from django.shortcuts import render, redirect, get_object_or_404
from . import forms
from django.core.paginator import Paginator
from django.db.models import Q
from django.contrib import messages
from inventario.models import Tecnology, Material_Didactico
from inventario import models
from django.contrib.auth.decorators import login_required
from django.contrib.auth import login
import matplotlib.pyplot as plt
import numpy as np
import pandas as pd
import base64
import io

def index(request):
    #valida que este logueado 
    if not request.session.get('is_authenticated'):
        return redirect('/ingresar/')  # Redirige si no está logueado

    id_usuario = request.session.get('user_id')

    try:
        usuario = models.User.objects.get(id_user=id_usuario)
    except models.User.DoesNotExist:
        return redirect('/ingresar/')  # Por si falla
    usuario = request.session.get('NombreUsuario','NO')
    
    context = {
        'user': usuario,
        'app': 'appBodega',
        'id_user': id_usuario,
        }
    return render(request, 'bodega.html', context) 

def newTecnologi(request):
    if not request.session.get('is_authenticated'):
        return redirect('/ingresar/') 

    user_id = request.session.get('user_id')

    try:
        usuario = models.User.objects.get(id_user=user_id)
    except models.User.DoesNotExist:
        return redirect('/ingresar/') 

    
    #formulario por metodo post
    if request.method == 'POST':
        form = forms.RegistroTecnologico(request.POST)
        if form.is_valid():
            form.save()
            messages.success(request, 'Elemento Registrado')
            return redirect('bodega:bodega')
        else:
            print(f'error: {form.errors}')
    else:
        form = forms.RegistroTecnologico()
    #busqueda
    search_query = request.GET.get('search','')
    #filtro de busqueda
    equipos = models.Tecnology.objects.select_related('idType_technologi').all()
    if usuario.id_rol.name_rol == 'gestorCentros':  # Si tienes ese rol
        equipos = Tecnology.objects.select_related('idType_technologi').all()
    else:
        equipos = Tecnology.objects.select_related('idType_technologi').filter(idUbication__id_centro=usuario.id_centro)
    if search_query:
        equipos = equipos.filter(
            Q(id_Place__name_place__icontains=search_query) | #busca por estado ya sea prestado, en bodega, manteniemiento, etc
            Q(idUbication__name_Ubication__icontains=search_query) | #busca por ubicaciones, biblioteca, oficinas, ambientes
            Q(series_Manufactures__icontains=search_query) | # busca por serial de fabrica
            Q(series_sena__icontains=search_query) # busca por serial del sena
        )
    #paginacion
    paginator = Paginator(equipos, 30)  
    page_number = request.GET.get('page')  
    page_obj = paginator.get_page(page_number) 
    return render(request, 'newTecnologia.html', {
        'form': form,
        'equipos': page_obj,  # Datos paginados
        'search_query': search_query  # Enviar búsqueda a la plantilla
    })


def newOtros(request):
    if not request.session.get('is_authenticated'):
        return redirect('/ingresar/')  

    user_id = request.session.get('user_id')

    try:
        usuario = models.User.objects.get(id_user=user_id)
    except models.User.DoesNotExist:
        return redirect('/ingresar/')  
    #formulario registro materiales
    if request.method == 'POST':
        form = forms.RegistroMateriales(request.POST)
        if form.is_valid():
            form.save()
            messages.success(request, 'Elemento Registrado')
            return redirect('bodega:bodega')
        else:
            print(form.errors)
    else:
        form =forms.RegistroMateriales()
    #obtiene la busqueda
    search_query = request.GET.get('search','')
     #filtro de busqueda
    materiales = models.Material_Didactico.objects.select_related('id_Place').all()
    if usuario.id_rol.name_rol == 'gestorCentros':  # Si tienes ese rol
        materiales = Material_Didactico.objects.select_related('id_Place').all()
    else:
        materiales = Material_Didactico.objects.select_related('id_Place').filter(idUbication__id_centro=usuario.id_centro)
    
    if search_query:
        materiales = materiales.filter(
            Q(series_Manufactures__icontains=search_query) |
            Q(series_sena__icontains=search_query) |
            Q(name_material__icontains=search_query)
        )
    #PAGINACION
    paginator = Paginator(materiales, 30)  
    page_number = request.GET.get('page')  
    page_obj = paginator.get_page(page_number)  

    return render(request, 'newOtros.html', {
        'form': form,
        'materiales': page_obj,  # Datos paginados
        'search_query': search_query  # Enviar búsqueda a la plantilla
    })

def newUbication(request):
    if not request.session.get('is_authenticated'):
        return redirect('/ingresar/') 

    user_id = request.session.get('user_id')

    try:
        usuario = models.User.objects.get(id_user=user_id)
    except models.User.DoesNotExist:
        return redirect('/ingresar/')  
    # Manejo del formulario
    if request.method == 'POST':
        form = forms.RegistroUbicacion(request.POST)
        if form.is_valid():
            form.save()
            messages.success(request, 'Ubicación Registrada')
            return redirect('bodega:bodega') 
        else:
            print(form.errors)
            messages.error(request, 'Ubicación no registrada')
    else:
        form = forms.RegistroUbicacion()

    # OBTENER EL TÉRMINO DE BÚSQUEDA
    search_query = request.GET.get('search', '')

    #FILTRAR UBICACIONES SI HAY BÚSQUEDA
    ubicaciones = models.Ubication.objects.select_related('id_centro').all()
    # if usuario.id_rol.name_rol == 'gestorCentros':  # Si tienes ese rol
    #     ubicaciones = Material_Didactico.objects.select_related('id_Place').all()
    # else:
    #     materiales = Material_Didactico.objects.select_related('id_Place').filter(idUbication__id_centro=usuario.id_centro)
    if search_query:
        ubicaciones = ubicaciones.filter(
            Q(name_Ubication__icontains=search_query) |  # Buscar por nombre de la ubicación
            Q(id_centro__name_centro__icontains=search_query)  # Buscar por nombre del centro
        )

    # PAGINACIÓN (30 ELEMENTOS POR PGINA)
    paginator = Paginator(ubicaciones, 30)  
    page_number = request.GET.get('page')  
    page_obj = paginator.get_page(page_number)  

    return render(request, 'newUbication.html', {
        'form': form,
        'ubicaciones': page_obj,  # Datos paginados
        'search_query': search_query  # Enviar búsqueda a la plantilla
    })

def prestamo(request):
    if not request.session.get('is_authenticated'):
        return redirect('/ingresar/')  

    id_usuario = request.session.get('user_id')

    try:
        usuario = models.User.objects.get(id_user=id_usuario)
    except models.User.DoesNotExist:
        return redirect('/ingresar/')
    if request.method == 'POST':
        form = forms.Prestamo(request.POST)
        if form.is_valid():
            form.save()
            messages.success(request, 'Prestamo Registrado')
            return redirect('bodega:bodega')
        else:
            print(form.errors)
            messages.error(request, 'Prestamo no registrado')
    else:
        form = forms.Prestamo()
    return render(request, 'prestamo.html',{'form': form})


def visualizar(request, id):
    if not request.session.get('is_authenticated'):
        return redirect('/ingresar/')  

    id_usuario = request.session.get('user_id')

    try:
        usuario = models.User.objects.get(id_user=id_usuario)
    except models.User.DoesNotExist:
        return redirect('/ingresar/')
    tecnologias = models.Tecnology.objects.filter(idTecnology=id).select_related('idType_technologi').first()
    context = {
        'tecnologias': tecnologias,  #
    }
    return render(request, 'visualizar.html', context)


def actualizarTecnologia(request, id):
    if not request.session.get('is_authenticated'):
        return redirect('/ingresar/')  

    id_usuario = request.session.get('user_id')

    try:
        usuario = models.User.objects.get(id_user=id_usuario)
    except models.User.DoesNotExist:
        return redirect('/ingresar/')
    
    tecnologia = get_object_or_404(models.Tecnology, idTecnology=id)
    
    if request.method == 'POST':
        form = forms.RegistroTecnologico(request.POST, instance=tecnologia)
        if form.is_valid():
            form.save()
            messages.success(request, 'Tecnología actualizada exitosamente')
            return redirect('bodega:bodega')
        else:
            messages.error(request, 'Error al actualizar la tecnología')
    else:
        form = forms.RegistroTecnologico(instance=tecnologia)

    return render(request, 'actualiza-equipo.html', {'form': form, 'tecnologia': tecnologia})


def visualizarMaterial(request, id):
    if not request.session.get('is_authenticated'):
        return redirect('/ingresar/')  

    id_usuario = request.session.get('user_id')

    try:
        usuario = models.User.objects.get(id_user=id_usuario)
    except models.User.DoesNotExist:
        return redirect('/ingresar/')
    
    material = get_object_or_404(models.Material_Didactico, idMaterial_didactico=id)
    
    context = {
        'material': material,  #
    }
    return render(request, 'visualizar-didactico.html', context)



def actualizarMaterial(request, id):
    if not request.session.get('is_authenticated'):
        return redirect('/ingresar/')  

    id_usuario = request.session.get('user_id')

    try:
        usuario = models.User.objects.get(id_user=id_usuario)
    except models.User.DoesNotExist:
        return redirect('/ingresar/')
    
    material = get_object_or_404(models.Material_Didactico, idMaterial_didactico=id)
    
    if request.method == 'POST':

appBodega/templates/bodega.html
{% extends 'plantilla.html' %}
{% load static %}
{% block title %}Almacen{% endblock %}
{% block contenido %}
{% if messages %}
{% for message in messages %}

<script>
    Swal.fire({
        title: "info",
        text: "{{ message }}!",
        icon: "info"
    });
</script>
{% endfor %}
{% endif %}
        <div class="categories">
            <div class="category">
                <a onclick="modifitInventari()" >
                    <i id="textOnclick" class="fa-solid fa-paperclip"></i>
                    <p id="textOnclick">Modificar Inventario</p>
                </a>
            </div>
            <div class="category">
                <a href="{% url 'appBodega:newUbication' %}">
                    <i class="fa-solid fa-location-dot"></i>
                    <p>Agregar Ubicación</p>
                </a>
            </div>
            <div class="category">
                <a href="{% url 'appBodega:prestamo' %}">
                    <i class="fa-solid fa-handshake-simple"></i>
                    <p>Prestar Elemento</p>
                </a>
            </div>
            <div class="category">
                <a href="{% url 'appBodega:mesaAyuda' %}">
                    <i class="fa-solid fa-circle-exclamation"></i>
                    <p>Mesa de Ayuda</p>
                </a>
            </div>
            <div class="category">
                <a href="">
                    <i class="fa-solid fa-triangle-exclamation"></i>
                    <p>Alertas y Novedades</p>
                </a>
            </div>
        </div>
{% endblock %}

appBodega/templates/newOtros.html
{% extends 'plantilla.html' %}
{% load static %}
{% block title %} Tecnologia {% endblock %}
{% block p %}
<h1>Inventariar otros Materiales</h1>
<br>
{% endblock %}

{% block menuoptions %}
<li class="nav-item">
    <a class="nav-link active" aria-current="page" href="{% url 'appBodega:bodega' %}">Regresar</a>
</li>
{% endblock %}
{% block contenido %}

{% if messages %}
{% for message in messages %}
<script>
    Swal.fire({
        title: "info",
        text: "{{ message }}!",
        icon: "info"
    });
</script>
{% endfor %}
{% endif %}
<div class="container-fluid">
<div class="row">
    <div class="col-md-8">
        <div class="container_tablaUser" style="height: 100%;">
            <form method="GET" action="{% url 'appBodega:newOtros' %}" class="mb-3">
                <div class="input-group">
                    <input type="text" name="search" class="form-control" placeholder="Buscar por Seriales o Nombre" 
                           value="{{ search_query }}">
                    <button type="submit" class="btn btn-primary">Buscar</button>
                </div>
            </form>
            
            <!-- Tabla de Ubicaciones -->
            <table class="table table-hover table-striped table-responsive">
                <thead class="table-dark">
                    <tr>
                        <th scope="col">Nombre</th>
                        <th scope="col">Descripción</th>
                        <th scope="col">Cantidad</th>
                        <th scope="col">Serial Fabrica</th>
                        <th scope="col">Serial Sena</th>
                        <th scope="col">Acciones</th>
                    </tr>
                </thead>
                <tbody>
                    {% for ubi in materiales %}
                    <tr>
                        <td>{{ ubi.name_material }}</td>
                        <td>{{ ubi.description }}</td>
                        <td>{{ ubi.quantity }}</td>
                        <td>{{ ubi.series_Manufactures }}</td>
                        <td>{{ ubi.series_sena }}</td>
                        <td><a href="{% url 'appBodega:detalleOtros' ubi.idMaterial_didactico %}" class="btn btn-sm btn-primary">Visualizar</a></td>
                    </tr>
                    {% empty %}
                    <tr>
                        <td colspan="6">No se encontraron resultados.</td>
                    </tr>
                    {% endfor %}
                </tbody>
            </table>
            
            <!-- PAGINACIÓN con búsqueda -->
            <div class="pagination">
                <span class="step-links">
                    {% if materiales.has_previous %}
                        <a href="?page=1&search={{ search_query }}">&laquo; Primera</a>
                        <a href="?page={{ materiales.previous_page_number }}&search={{ search_query }}">Anterior</a>
                    {% endif %}
            
                    <span class="current">
                        Página {{ materiales.number }} de {{ materiales.paginator.num_pages }}.
                    </span>
            
                    {% if materiales.has_next %}
                        <a href="?page={{ materiales.next_page_number }}&search={{ search_query }}">Siguiente</a>
                        <a href="?page={{ materiales.paginator.num_pages }}&search={{ search_query }}">Última &raquo;</a>
                    {% endif %}
                </span>
            </div>
        </div>
    </div><br><br><br>
    <div class="col-md-4">
        <div class="container_form">
            <form id="registrationForm" method="post">
                {% csrf_token %}
                {% for field in form %}
                <div id="step1" class="form-group">
                    <label for="{{ field.id_for_label }}" class="">{{ field.label }}</label>
                    {{field}}
                </div>
                {% endfor %}
                <div class="buttons">
                    <button type="submit">Enviar</button>
                </div>
            </form>
        </div>
    </div>
</div>
</div>
{% endblock %}
{% block estadistics %}
 {% endblock %}

appBodega/templates/newTecnologia.html
{% extends 'plantilla.html' %}
{% load static %}
{% block title %} Tecnologia {% endblock %}
{% block p %}
<h1>Inventario Tecnologico</h1>
<br>
{% endblock %}

{% block menuoptions %}
<li class="nav-item">
    <a class="nav-link active" aria-current="page" href="{% url 'appBodega:bodega' %}">Regresar</a>
</li>
{% endblock %}
{% block contenido %}

{% if messages %}
{% for message in messages %}
<script>
    Swal.fire({
        title: "info",
        text: "{{ message }}!",
        icon: "info"
    });
</script>
{% endfor %}
{% endif %}
<div class="container-fluid">
<div class="row">
    <div class="col-md-8">
        <div class="container_tablaUser" style="height: 100%;">
            <form method="GET" action="{% url 'appBodega:newTecnologi' %}" class="mb-3">
                <div class="input-group">
                    <input type="text" name="search" class="form-control" placeholder="Buscar ubicación o centro..." 
                           value="{{ search_query }}">
                    <button type="submit" class="btn btn-primary">Buscar</button>
                </div>
            </form>
            
            <!-- Tabla de Ubicaciones -->
            <table class="table table-hover table-striped table-responsive">
                <thead class="table-dark">
                    <tr>
                        <th scope="col">Tipo</th>
                        <th scope="col">Marca</th>
                        <th scope="col">Serial Fabria</th>
                        <th scope="col">Serial Sena</th>
                        <th scope="col">Ubicación</th>
                        <th scope="col">Acciones</th>
                    </tr>
                </thead>
                <tbody>
                    {% for ubi in equipos %}
                    <tr>
                        <td>{{ ubi.idType_technologi.name_technologi }}</td>  <!-- Muestra el nombre del centro -->
                        <td>{{ ubi.idMarke.name_marke }}</td>
                        <td>{{ ubi.series_Manufactures }}</td>
                        <td>{{ ubi.series_sena }}</td>
                        <td>{{ ubi.idUbication.name_Ubication }}</td>
                        <td><a href="{% url 'appBodega:detalles' ubi.idTecnology %}" class="btn btn-sm btn-primary">Visualizar</a></td>
                    </tr>
                    {% empty %}
                    <tr>
                        <td colspan="6">No se encontraron resultados.</td>
                    </tr>
                    {% endfor %}
                </tbody>
            </table>
            
            <!-- PAGINACIÓN con búsqueda -->
            <div class="pagination">
                <span class="step-links">
                    {% if ubicaciones.has_previous %}
                        <a href="?page=1&search={{ search_query }}">&laquo; Primera</a>
                        <a href="?page={{ ubicaciones.previous_page_number }}&search={{ search_query }}">Anterior</a>
                    {% endif %}
            
                    <span class="current">
                        Página {{ ubicaciones.number }} de {{ ubicaciones.paginator.num_pages }}.
                    </span>
            
                    {% if ubicaciones.has_next %}
                        <a href="?page={{ ubicaciones.next_page_number }}&search={{ search_query }}">Siguiente</a>
                        <a href="?page={{ ubicaciones.paginator.num_pages }}&search={{ search_query }}">Última &raquo;</a>
                    {% endif %}
                </span>
            </div>
        </div>
    </div><br><br><br>
    <div class="col-md-4">
        <div class="container_form">
            <form id="registrationForm" method="post">
                {% csrf_token %}
                {% for field in form %}
                <div id="step1" class="form-group">
                    <label for="{{ field.id_for_label }}" class="">{{ field.label }}</label>
                    {{field}}
                </div>
                {% endfor %}
                <div class="buttons">
                    <button type="submit">Enviar</button>
                </div>
            </form>
        </div>
    </div>
</div>
</div>
{% endblock %}
{% block estadistics %}
 {% endblock %}

appBodega/templates/prestamo.html
{% extends 'plantilla.html' %}

{% block title %}Prestamo{% endblock %}
{% block p %}<h1> Elementos prestados </h1><br>{% endblock %}
{% block menuoptions %}
<li class="nav-item">
    <a class="nav-link active" aria-current="page" href="{% url 'appBodega:bodega' %}">Regresar</a>
</li>
{% endblock %}
{% block contenido %}
<div class="container-fluid">
    <div class="row">
        <div class="col-md-7">
            <div class="container_tablaUser" style="height: 100%;">
                <form method="GET" action="{% url 'appBodega:prestamo' %}" class="mb-3">
                    <div class="input-group">
                        <input type="text" name="search" class="form-control" placeholder="Buscar por usuario o seriales"
                            value="{{ search_query }}">
                        <button type="submit" class="btn btn-primary">Buscar</button>
                    </div>
                </form>

                <!-- Tabla de Ubicaciones -->
                <table class="table table-hover table-striped table-responsive">
                    <thead class="table-dark">
                        <tr>
                            <th scope="col">Fecha</th>
                            <th scope="col">Usuario</th>
                            <th scope="col">Elemento Prestado</th>
                            <th scope="col">Acciones</th>
                        </tr>
                    </thead>
                    <tbody>
                        {% for ubi in equipos %}
                        <tr>
                            <td>{{ ubi.idType_technologi.name_technologi }}</td> <!-- Muestra el nombre del centro -->
                            <td>{{ ubi.idMarke.name_marke }}</td>
                            <td>{{ ubi.series_Manufactures }}</td>
                            <td><a href="{% url 'appBodega:detalles' %}" class="btn btn-sm btn-primary">Visualizar</a></td>
                        </tr>
                        {% empty %}
                        <tr>
                            <td colspan="6">No se encontraron resultados.</td>
                        </tr>
                        {% endfor %}
                    </tbody>
                </table>

                <!-- PAGINACIÓN con búsqueda -->
                <div class="pagination">
                    <span class="step-links">
                        {% if ubicaciones.has_previous %}
                        <a href="?page=1&search={{ search_query }}">&laquo; Primera</a>
                        <a href="?page={{ ubicaciones.previous_page_number }}&search={{ search_query }}">Anterior</a>
                        {% endif %}

                        <span class="current">
                            Página {{ ubicaciones.number }} de {{ ubicaciones.paginator.num_pages }}.
                        </span>

                        {% if ubicaciones.has_next %}
                        <a href="?page={{ ubicaciones.next_page_number }}&search={{ search_query }}">Siguiente</a>
                        <a href="?page={{ ubicaciones.paginator.num_pages }}&search={{ search_query }}">Última
                            &raquo;</a>
                        {% endif %}
                    </span>
                </div>
            </div>
           
        </div>
        <div class="col-md-4">
            <div class="container_form">
                <form id="registrationForm" method="post">
                    {% csrf_token %}
                    {% for field in form %}
                    <div id="step1" class="form-group">
                        <label for="{{ field.id_for_label }}" class="">{{ field.label }}</label>
                        {{field}}
                    </div>
                    {% endfor %}
                    <div class="buttons">
                        <button type="submit">Enviar</button>
                    </div>
                </form>
            </div>
        </div>
    </div>
</div>
        {% endblock %}
        {% block estadistics %}
 {% endblock %}